// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common_protoc/body.proto

package go_gens

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Platform int32

const (
	Platform_UNKNOWN      Platform = 0
	Platform_IOS          Platform = 1
	Platform_ANDROID      Platform = 2
	Platform_ELECTRON_MAC Platform = 3
	Platform_ELECTRON_WIN Platform = 4
	Platform_WEB_ADMIN    Platform = 5
)

var Platform_name = map[int32]string{
	0: "UNKNOWN",
	1: "IOS",
	2: "ANDROID",
	3: "ELECTRON_MAC",
	4: "ELECTRON_WIN",
	5: "WEB_ADMIN",
}

var Platform_value = map[string]int32{
	"UNKNOWN":      0,
	"IOS":          1,
	"ANDROID":      2,
	"ELECTRON_MAC": 3,
	"ELECTRON_WIN": 4,
	"WEB_ADMIN":    5,
}

func (x Platform) String() string {
	return proto.EnumName(Platform_name, int32(x))
}

func (Platform) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d728edc81b13ff07, []int{0}
}

type Device struct {
	SystemVersion        string          `protobuf:"bytes,1,opt,name=systemVersion,proto3" json:"systemVersion,omitempty"`
	Model                string          `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Brand                string          `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Display              *Device_Display `protobuf:"bytes,4,opt,name=display,proto3" json:"display,omitempty"`
	Imei                 string          `protobuf:"bytes,5,opt,name=imei,proto3" json:"imei,omitempty"`
	DeviceLock           string          `protobuf:"bytes,6,opt,name=deviceLock,proto3" json:"deviceLock,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_d728edc81b13ff07, []int{0}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetSystemVersion() string {
	if m != nil {
		return m.SystemVersion
	}
	return ""
}

func (m *Device) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Device) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *Device) GetDisplay() *Device_Display {
	if m != nil {
		return m.Display
	}
	return nil
}

func (m *Device) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *Device) GetDeviceLock() string {
	if m != nil {
		return m.DeviceLock
	}
	return ""
}

type Device_Display struct {
	Width                int32    `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device_Display) Reset()         { *m = Device_Display{} }
func (m *Device_Display) String() string { return proto.CompactTextString(m) }
func (*Device_Display) ProtoMessage()    {}
func (*Device_Display) Descriptor() ([]byte, []int) {
	return fileDescriptor_d728edc81b13ff07, []int{0, 0}
}

func (m *Device_Display) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device_Display.Unmarshal(m, b)
}
func (m *Device_Display) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device_Display.Marshal(b, m, deterministic)
}
func (m *Device_Display) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device_Display.Merge(m, src)
}
func (m *Device_Display) XXX_Size() int {
	return xxx_messageInfo_Device_Display.Size(m)
}
func (m *Device_Display) XXX_DiscardUnknown() {
	xxx_messageInfo_Device_Display.DiscardUnknown(m)
}

var xxx_messageInfo_Device_Display proto.InternalMessageInfo

func (m *Device_Display) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Device_Display) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Header struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Device               *Device  `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	Platform             Platform `protobuf:"varint,3,opt,name=platform,proto3,enum=codesprite.Platform" json:"platform,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,5,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	Timestamp            int64    `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AppID                uint32   `protobuf:"varint,7,opt,name=appID,proto3" json:"appID,omitempty"`
	AppVer               string   `protobuf:"bytes,8,opt,name=appVer,proto3" json:"appVer,omitempty"`
	AppBuildVer          uint32   `protobuf:"varint,9,opt,name=appBuildVer,proto3" json:"appBuildVer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_d728edc81b13ff07, []int{1}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Header) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *Header) GetPlatform() Platform {
	if m != nil {
		return m.Platform
	}
	return Platform_UNKNOWN
}

func (m *Header) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Header) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *Header) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Header) GetAppID() uint32 {
	if m != nil {
		return m.AppID
	}
	return 0
}

func (m *Header) GetAppVer() string {
	if m != nil {
		return m.AppVer
	}
	return ""
}

func (m *Header) GetAppBuildVer() uint32 {
	if m != nil {
		return m.AppBuildVer
	}
	return 0
}

type Request struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *any.Any `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_d728edc81b13ff07, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Request) GetBody() *any.Any {
	if m != nil {
		return m.Body
	}
	return nil
}

type Response struct {
	Header               *Header       `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *any.Any      `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Ret                  *Response_Ret `protobuf:"bytes,3,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d728edc81b13ff07, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Response) GetBody() *any.Any {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Response) GetRet() *Response_Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

type Response_Ret struct {
	Code                 uint64   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Ret) Reset()         { *m = Response_Ret{} }
func (m *Response_Ret) String() string { return proto.CompactTextString(m) }
func (*Response_Ret) ProtoMessage()    {}
func (*Response_Ret) Descriptor() ([]byte, []int) {
	return fileDescriptor_d728edc81b13ff07, []int{3, 0}
}

func (m *Response_Ret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Ret.Unmarshal(m, b)
}
func (m *Response_Ret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Ret.Marshal(b, m, deterministic)
}
func (m *Response_Ret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Ret.Merge(m, src)
}
func (m *Response_Ret) XXX_Size() int {
	return xxx_messageInfo_Response_Ret.Size(m)
}
func (m *Response_Ret) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Ret.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Ret proto.InternalMessageInfo

func (m *Response_Ret) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response_Ret) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("codesprite.Platform", Platform_name, Platform_value)
	proto.RegisterType((*Device)(nil), "codesprite.Device")
	proto.RegisterType((*Device_Display)(nil), "codesprite.Device.Display")
	proto.RegisterType((*Header)(nil), "codesprite.Header")
	proto.RegisterType((*Request)(nil), "codesprite.Request")
	proto.RegisterType((*Response)(nil), "codesprite.Response")
	proto.RegisterType((*Response_Ret)(nil), "codesprite.Response.Ret")
}

func init() { proto.RegisterFile("common_protoc/body.proto", fileDescriptor_d728edc81b13ff07) }

var fileDescriptor_d728edc81b13ff07 = []byte{
	// 578 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xfd, 0x5c, 0xe7, 0x77, 0xd2, 0x7e, 0xb2, 0x56, 0x15, 0x32, 0x11, 0x42, 0x51, 0x00, 0x29,
	0x2a, 0x92, 0x83, 0x02, 0x12, 0x17, 0x5c, 0xa5, 0x4d, 0x25, 0x22, 0x5a, 0x07, 0x2d, 0xa5, 0x95,
	0xb8, 0x31, 0x4e, 0x3c, 0x8d, 0xad, 0xc6, 0xde, 0x65, 0x77, 0x03, 0xca, 0x0b, 0xf1, 0x0e, 0x3c,
	0x1c, 0x12, 0xda, 0xb1, 0x43, 0x13, 0xb8, 0xe6, 0xca, 0x73, 0xce, 0x9c, 0x9d, 0x99, 0x3d, 0x3b,
	0x06, 0x7f, 0x21, 0xf2, 0x5c, 0x14, 0x91, 0x54, 0xc2, 0x88, 0xc5, 0x70, 0x2e, 0x92, 0x4d, 0x40,
	0x31, 0x83, 0x85, 0x48, 0x50, 0x4b, 0x95, 0x19, 0xec, 0x3e, 0x5c, 0x0a, 0xb1, 0x5c, 0xe1, 0x90,
	0x32, 0xf3, 0xf5, 0xed, 0x30, 0x2e, 0x2a, 0x59, 0xff, 0xa7, 0x03, 0x8d, 0x09, 0x7e, 0xcd, 0x16,
	0xc8, 0x9e, 0xc2, 0x91, 0xde, 0x68, 0x83, 0xf9, 0x35, 0x2a, 0x9d, 0x89, 0xc2, 0x77, 0x7a, 0xce,
	0xa0, 0xcd, 0xf7, 0x49, 0x76, 0x0c, 0xf5, 0x5c, 0x24, 0xb8, 0xf2, 0x0f, 0x28, 0x5b, 0x02, 0xcb,
	0xce, 0x55, 0x5c, 0x24, 0xbe, 0x5b, 0xb2, 0x04, 0xd8, 0x2b, 0x68, 0x26, 0x99, 0x96, 0xab, 0x78,
	0xe3, 0xd7, 0x7a, 0xce, 0xa0, 0x33, 0xea, 0x06, 0xf7, 0x53, 0x05, 0x65, 0xdb, 0x60, 0x52, 0x2a,
	0xf8, 0x56, 0xca, 0x18, 0xd4, 0xb2, 0x1c, 0x33, 0xbf, 0x4e, 0xa5, 0x28, 0x66, 0x8f, 0x01, 0x12,
	0x92, 0x5f, 0x88, 0xc5, 0x9d, 0xdf, 0xa0, 0xcc, 0x0e, 0xd3, 0x7d, 0x0d, 0xcd, 0xaa, 0x8e, 0x1d,
	0xe5, 0x5b, 0x96, 0x98, 0x94, 0xc6, 0xaf, 0xf3, 0x12, 0xb0, 0x07, 0xd0, 0x48, 0x31, 0x5b, 0xa6,
	0x86, 0xe6, 0xae, 0xf3, 0x0a, 0xf5, 0xbf, 0x1f, 0x40, 0xe3, 0x2d, 0xc6, 0x09, 0x2a, 0x2b, 0x59,
	0x6b, 0x54, 0xd3, 0x84, 0x4e, 0xba, 0xbc, 0x42, 0xec, 0x04, 0x1a, 0x65, 0x27, 0x3a, 0xda, 0x19,
	0xb1, 0xbf, 0x2f, 0xc1, 0x2b, 0x05, 0x7b, 0x01, 0x2d, 0xb9, 0x8a, 0xcd, 0xad, 0x50, 0x39, 0x59,
	0xf1, 0xff, 0xe8, 0x78, 0x57, 0xfd, 0xbe, 0xca, 0xf1, 0xdf, 0x2a, 0x3b, 0xae, 0x11, 0x77, 0x58,
	0x90, 0x43, 0x6d, 0x5e, 0x02, 0xd6, 0x87, 0x43, 0x85, 0xb7, 0x0a, 0x75, 0x7a, 0x45, 0xc9, 0xd2,
	0x8b, 0x3d, 0x8e, 0x3d, 0x82, 0xb6, 0xc9, 0x72, 0xd4, 0x26, 0xce, 0x25, 0x59, 0xe2, 0xf2, 0x7b,
	0xc2, 0xd6, 0x8d, 0xa5, 0x9c, 0x4e, 0xfc, 0x66, 0xcf, 0x19, 0x1c, 0xf1, 0x12, 0xd8, 0x3b, 0xc6,
	0x52, 0x5e, 0xa3, 0xf2, 0x5b, 0x54, 0xb1, 0x42, 0xac, 0x07, 0x9d, 0x58, 0xca, 0xd3, 0x75, 0xb6,
	0x4a, 0x6c, 0xb2, 0x4d, 0x67, 0x76, 0xa9, 0x7e, 0x04, 0x4d, 0x8e, 0x5f, 0xd6, 0xa8, 0x8d, 0x35,
	0x24, 0x25, 0xcb, 0xc8, 0xa8, 0x3f, 0x0c, 0x29, 0xcd, 0xe4, 0x95, 0x82, 0x0d, 0xa0, 0x66, 0x97,
	0xb2, 0xb2, 0xee, 0x38, 0x28, 0x37, 0x31, 0xd8, 0x6e, 0x62, 0x30, 0x2e, 0x36, 0x9c, 0x14, 0xfd,
	0x1f, 0x0e, 0xb4, 0x38, 0x6a, 0x29, 0x0a, 0x8d, 0xff, 0xa6, 0x05, 0x3b, 0x01, 0x57, 0xa1, 0xa1,
	0x87, 0xe9, 0x8c, 0xfc, 0xdd, 0x92, 0xdb, 0xc6, 0x01, 0x47, 0xc3, 0xad, 0xa8, 0xfb, 0x1c, 0x5c,
	0x8e, 0xc6, 0x2e, 0xa3, 0x95, 0xd1, 0x18, 0x35, 0x4e, 0x31, 0xf3, 0xc0, 0xcd, 0xf5, 0xb2, 0xfa,
	0x01, 0x6c, 0x78, 0xf2, 0x19, 0x5a, 0xdb, 0xa7, 0x65, 0x1d, 0x68, 0x7e, 0x0c, 0xdf, 0x85, 0xb3,
	0x9b, 0xd0, 0xfb, 0x8f, 0x35, 0xc1, 0x9d, 0xce, 0x3e, 0x78, 0x8e, 0x65, 0xc7, 0xe1, 0x84, 0xcf,
	0xa6, 0x13, 0xef, 0x80, 0x79, 0x70, 0x78, 0x7e, 0x71, 0x7e, 0x76, 0xc5, 0x67, 0x61, 0x74, 0x39,
	0x3e, 0xf3, 0xdc, 0x3d, 0xe6, 0x66, 0x1a, 0x7a, 0x35, 0x76, 0x04, 0xed, 0x9b, 0xf3, 0xd3, 0x68,
	0x3c, 0xb9, 0x9c, 0x86, 0x5e, 0xfd, 0xf4, 0xd9, 0xa7, 0x27, 0x26, 0xcd, 0x74, 0xa4, 0x50, 0x0a,
	0x9d, 0x19, 0xb5, 0x89, 0x64, 0x6c, 0xd2, 0xe1, 0x52, 0x44, 0x4b, 0x2c, 0xf4, 0x9b, 0xea, 0x3b,
	0x6f, 0xd0, 0xad, 0x5f, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x30, 0x02, 0x6e, 0xba, 0x18, 0x04,
	0x00, 0x00,
}
